hoprnet/admin-ui

- src/commands/closeChannel.ts
Current smart contract does not support closing incoming channel. To distinguish between a common error and this known issue, now UI returns "UNSUPPORTED_FEATURE" when closing an incoming channel.
> Return detailed error status when closing channel

- src/router.tsx
- src/sections/info.tsx
- src/sections/selectNode.tsx
- src/store/slices/auth/actionsAsync.ts
- src/store/slices/auth/index.ts
- src/store/slices/auth/initialState.ts
This was an error that stricter types could have caught. some values on auth state still had `ip` and `apiKey` but the actions were sending `apiToken` and `apiEndpoint`. With this pr it will fix that and prevent this from happening on auth slice.
> fix types in auth state

- package.json
- src/sections/selectNode.tsx
- src/store/index.ts
- src/store/slices/node/actionsAsync.ts
- src/store/slices/node/index.ts
- src/store/slices/node/initialState.ts
- src/store/slices/node/websocketMiddleware.ts
- src/types/store.ts
- yarn.lock
closes #19 
[Redux middleware](https://redux.js.org/understanding/history-and-design/middleware#the-final-approach) it provides a third-party extension point between dispatching an action, and the moment it reaches the reducer. So when a initializeWebsocket action is triggered it will first run run through the middleware creating a websocket connection before reaching the actual reducer.
The WebSocket instance is not serializable and thus technically not something that should be stored in Redux state. So there were 2 alternatives considered in this pr:
With this solution we could have an easy way to mount ws connection and tear it down, however there are a lot of concepts the team would need to learn and it also provides less customization. 
Even though this solution is more code, the …
> Ws connection middleware for redux

- src/router.tsx
- src/sections/peers.tsx
Closes #21
This pull Request provides peers subpage to show the announces peers with their info
Things to be added:
To be noted:
Elegible is currently set to show true if the peerId is connected to the current node (in both the announced and connected arrays of peers)
> Peers subpage

- src/sections/channels.tsx
Closes #63
This pull request aims to fix the bugs on the admin subpage: Channels.
Fixes expected:
> Fix loggin out credential bug and the # in the url error

- src/router.tsx
- src/sections/settings.tsx
Fixes #59
This pull request adds the settings of the hoprd node to the admin UI, allowing changes easily.
"includeRecipient"
"strategy"
}
> Settings subpage

- src/router.tsx
- src/store/slices/node/index.ts
- src/store/slices/node/initialState.ts
- src/store/slices/node/websocketMiddleware.ts
fixes #65 
after refreshing the page ws connections are re-established.
now the ws status is not determined by a boolean but by a string type union, giving us the flexibility to add more statuses if needed but right now we can determine if a ws is connecting | connected | error
> Reconnect ws on page refresh

- src/router.tsx
- src/sections/metrics.tsx
A way to read the prometheus string in exposition format to properly show metrics to the users and not a big string within a `<pre>` tag
```
Metric: connect_counter_client_relayed_packets
Description: Number of relayed packets (TURN client)
Type: counter
Value: 11048
Metric: connect_counter_direct_packets
Description: Number of directly sent packets (TCP)
Type: counter
Value: 725248
Metric: connect_counter_failed_conns
Description: Number of failed connection attempts
Type: counter
Value: 1247
Metric: connect_counter_failed_direct_dials
Description: Number of failed direct dials
Type: counter
Value: 8262
Metric: connect_counter_failed_relay_reqs
Description: Number of failed incoming relay requests
Type: counter
Value: 0
Metric: connect_counter_failed_relayed_dials
Description: Number of …
```
> Subpage: Metrics

- src/components/Faq/index.tsx
Faq component that takes a `variant` that can be `'blue'` or `'pink'` and changes the Accordion's colors based on that, a `label` which will be displayed as a Chip and `data`, an array of objects with `id`, `title` and `content` representing each Faq item.
```jsx
<Faq
variant="blue"
label="Allocating funds"
data={[
{
id: 0,
title: 'Token Addreses',
content: 'Lorem ipsum dolor sit amet.',
},
{
id: 1,
title: 'Buying xDAI & HOPR',
content: 'Consectetur adipiscing elit.',
},
{
id: 2,
title: 'Wrapping xHOPR → wxHOPR',
content: 'Suspendisse malesuada lacus.',
},
{
id: 3,
title: 'How much xDAI to move',
content: 'Sit amet blandit leo lobortis eget.',
},
{
id: 4,
title: 'Suggested usage profiles',
content: 'Hello world.',
},
]}
/>;
```
> Component: FAQ

- src/router.tsx
- src/sections/safe-transaction-history.tsx
- src/utils/helpers.ts
- yarn.lock
closes #112 
adds a page that shows **all** safe transactions, including the ones that did not run
- fetching all safe transactions requires adding pagination features to redux, right now it only fetches 20
- pagination in the table 
- module transactions
> Add Safe transaction history

- src/store/slices/safe/actionsAsync.ts
closes #121 
Proposing a new tx will always now have a valid nonce
1. safe nonce: 1
2. first proposed tx nonce: 1
3. second proposed tx nonce: 2
4. third proposed tx nonce: 3
This allows us to propose different transactions but the order is important. Since the safe nonce is 1 we should only interact with that one. 
The way rejections seem to work makes it impossible to reject a future nonce transaction.
we should disable future nonce interaction in #119
> Safe transactions increment nonce

- src/hooks/useWatcher/balances.ts
- src/hooks/useWatcher/index.ts
closes #103 
Updates the node balances watcher and checks if a node has less than a certain minimum threshold and if so it will send a notification
Before we would only track when a balance increased but there was actually a hidden bug here, due to the fact that if we withdrew balance and then added balance again it would not send a notification. Meaning that notifications would only send if the balance was higher than the all time high since connecting to the node but not necessarily if we received more tokens. 
Also now that we track if balance decreases it is a simple addition to add a notification if the balance is less than a specified threshold.
> Watch low node balance

- src/components/ConnectSafe/index.tsx
- src/components/ConnectWeb3/index.tsx
closes #151 
Fixes safe account in app bar not updating with redux app. Removed local state that tracked selectedSafeAddress and now it only uses redux state variable.
- connect to a safe
- change mm account
- the expected result is that the safe account in app bar should reset
> Safe account in app bar not updating

- config.ts
- src/components/ConnectSafe/index.tsx
- src/components/ConnectWeb3/index.tsx
- src/sections/safe.tsx
- src/store/slices/safe/actionsAsync.ts
- src/utils/blockchain.ts
closes #107 
This pr shows how we can interact with smart contracts from a safe account. It specifically adds the functionality to set allowance of hopr token to hopr channels from the safe account.
Since the allowance actually comes from the holder of tokens which in this case would be the Safe. This means we have to use safe interactions like `proposeTransaction` and `executeTransaction`. To use these interactions we have to pass a specific type `SafeTransactionDataPartial`, which amongst other things contain `{ to: string; value: string; data: string; operation?: OperationType }`. 
So we create the encoded data for the transaction and then pass the data for safe to execute.
[inspiration](https://ethereum.stackexchange.com/questions/116761/how-to-send-erc20-erc721-tokens-using-safe-core- …
> set allowance for hopr token from safe

- src/sections/safePendingTransactions.tsx
- src/store/slices/safe/actionsAsync.ts
- src/store/slices/safe/index.ts
- src/store/slices/safe/initialState.ts
closes #160 
the functionality described in the issue already exists and was tested.
- rename  `safeDelegates` to `delegates`
- rename  `safeInfo` to `info`
> change names in safe redux slice

- src/sections/actions.tsx
- src/sections/safe.tsx
- src/utils/safeTransactions.ts
Remove the obligation to sign and execute when there is only 1 signature left. Instead allow the user to execute straight away because execution transactions already append a signature.
created `getUserActionForPendingTransaction` which can return 'EXECUTE' | 'SIGN' | null.
- Whenever this transaction returns 'EXECUTE' then the transaction is ready to run either because it has reached the minimum of transactions or because there is only 1 signature missing.
- It will return SIGN when more than 1 signature is missing and the connected account has not signed yet
- null basically means the user can not do anything because the user has already signed and more than 1 signature is missing.
Actions subpage has been updated to use the new functionality.
> Execute when only 1 signature is pending

- src/sections/actions.tsx
- src/utils/date.ts
closes #185 
dayjs parsing change, before instead of minute it would show month. This pr also includes a small aligning changes for ethereum history transactions
slight alignment on time and value
> Bugfix constant minute in actions subpage

- src/sections/actions.tsx
- src/sections/safe.tsx
- src/sections/safeWithdraw.tsx
- src/steps/xdaiToNode.tsx
- src/store/slices/safe/actionsAsync.ts
- src/utils/safeTransactions.ts
continuation of #177
In the the pr #177 we managed to check that we can execute proposed transactions when only 1 signature is pending. In this pr there is a new function `getUserCanSkipProposal ` which allows us to know if the safe has 1 threshold and transactions don't have to be proposed but can be directly executed by an owner.
- created createAndExecuteTransactionThunk
- created createAndExecuteContractTransactionThunk
- rename executeTransactionThunk to executePendingTransactionThunk because it required a transaction to exist.
creating and executing transactions can invalidate a pending transaction. It will run straight away and not in a future nonce, so it can indirectly reject a pending transaction.
> Update safe actions buttons and sections to use execute

- src/hooks/useWatcher/safeTransactions.ts
- src/providers/wagmi/index.tsx
Sets our public client to the rpc stated in our connected wallet. Fallbacks to wagmi public client if ethereum is not present in window.
If ethereum is present in window and the user just has a bad provider, wagmi will go to public client
> wagmi use wallet provider

- src/components/ConnectNode/modal.tsx
- src/future-hopr-lib-components/Modal/index.tsx
- src/hooks/useWatcher/balances.ts
- src/router.tsx
- src/sections/node/info.tsx
- src/store/slices/auth/actionsAsync.ts
- src/store/slices/node/actionsAsync.ts
- src/store/slices/node/websocketMiddleware.ts
closes #194 
changed the get loginThunk to catch more errors.
Sometimes i would see the error text get rendered twice mainly because the thunk would be in state `isFetching` and the redux condition would fail. So I added a `force` prop which would skip this condition.
```
{ condition: (_payload, { getState }) => {
if (_payload.force) {
return true;
}
const isFetching = getState().node.balances.isFetching;
if (isFetching) {
return false;
}
} },
```
> Fix error handling on connecting

- src/store/slices/node/actionsAsync.ts
This pull request fixes the bug encountered where the peer count would grow 2x whenever refreshed.
Closes #222
> Fix peer count growing 2x

- src/components/Stepper/index.tsx
closes #241 
Add a new state to steps to bridge the gap between completing a step and going to the next step.
> Stepper add last completed step

- src/components/Faq/staking-alerts.tsx
- src/components/Faq/staking-faq.tsx
- src/components/InfoBar/index.tsx
This pull request fixes how the FAQ for staking/ on boarding was shown
Now the routes are structured like: `/hub/onboarding#x` the x representing the step it is, so we adjusted to use this number to show the FAQ respectively.
There are some routes that are missing, these are:
- `/steps/stake`
- `/steps/xdai-to-safe`
- `/steps/update-your-node`
This is because we were not able to identify the step number they are represented by or if they are not needed anymore.
Fixes #263
> Fix Onboarding FAQ

- src/components/Faq/node-faq.tsx
- src/components/Faq/staking-alerts.tsx
- src/components/Faq/staking-faq.tsx
- src/future-hopr-lib-components/Layout/footer.jsx
- src/pages/PrivacyNotice.tsx
- src/pages/TermsOfService.tsx
- src/pages/staking-hub/landingPage.tsx
- src/router.tsx
Closes #293 #313 #314 
In this PR multiple issues have been addressed. Since they were mostly related, they were from fixing another, solved.
- The FAQ copy was updated and so were the FAQ urls.
- The links on the FAQ were added and so were the staking landing page. 
- To completely update the links from the landing page we had to make 2 new pages called `TermsOfService` and `PrivacyNotice` so that the footer has the links updated.
- Managing wxHopr allowance link is missing since there is no page yet. (`/staking/dashboard#node` 4th faq)
- noNodeAdded page has `Add node to your safe` link but couldn't find page being used.
- `STORE FUNDS WITH <COMPLETE SECURITY>` in landing page missing (not in figma)
- Some links redirect to the page as a new tab even when it's inside the same hopr admin …
> Update whole app links and FAQ links

- src/components/Modal/node/OpenOrFundChannelModal.tsx
- src/pages/node/aliases.tsx
- src/pages/node/channelsIncoming.tsx
- src/pages/node/channelsOutgoing.tsx
- src/pages/node/peers.tsx
Closes #343 
This PR corrects the modal placeholder and text to display 'peerAddress' instead of peerId.
Since the peer redux state does not have `peerAddress` yet, we left the field empty until this state becomes available
> Update open channel modal placeholder

- config.ts
- src/components/InfoBar/details.tsx
- src/pages/node/info.tsx
closes #334 
- removed wxhopr from the infobar but it can still be seen on the info page.
> Remove wxhopr node admin

- src/pages/staking-hub/dashboard/index.tsx
Fixes #353 
When a client enters the dashboard, the initial screen that will appear will be the staking screen, although this works as intended, the FAQ component doesn't show because the `#staking` in the url is not present. This pull request adds said string to the url if the dashboard url doesn't have any `#` already.
> Add initial #staking hash if no hash is provided

- src/components/Modal/node/SendMessageModal.tsx
Fixed sending message trying to send with automatic path
- Removed redundant states 
```
const [automaticPath, set_automaticPath] = useState<boolean>(false);
const [directMessage, set_directMessage] = useState<boolean>(true);
```
This is now handled only by `sendMode`
- added another sendMode: `none` when nothing is selected.
> Refactor send message modal

- src/pages/staking-hub/dashboard/node.tsx
- src/pages/staking-hub/dashboard/staking.tsx
Fixes #372 
---
Staking:
Node:
> Move wxHopr Allowance to staking screen and rename

- package.json
- src/store/slices/safe/actionsAsync.ts
The previous setting set all permissions to BLOCK_ALL, preventing any node operations.
> Sets ALLOW_ALL on all Channel and Token operations by default.

- src/components/Modal/node/AddAliasModal.tsx
- src/components/Modal/node/OpenOrFundChannelModal.tsx
- src/components/Modal/node/PingModal.tsx
- src/components/Modal/node/SendMessageModal.tsx
- src/pages/node/aliases.tsx
Fixes #399 
This pull request adds the `disabled` prop to the Node Admin Modals:
Also it adds a check to Aliases page, where if peerId is equal to the node's hopr address, it disable all actions but the `remove alias`
> Add disabled prop to modals

- src/future-hopr-lib-components/Table/table-pro.tsx
- src/pages/node/aliases.tsx
- src/pages/node/channelsIncoming.tsx
- src/pages/node/channelsOutgoing.tsx
- src/pages/node/peers.tsx
closes #412 
Adds `copy` prop to headers and any header that has that prop active will copy text to clipboard and set tooltip to `Copied`
> Add double click to copy pro table

- src/components/ConnectNode/modal.tsx
Fixes #417 
This pull request adds a `parseAndFormatUrl` which checks if the apiEndpoint starts with either `http` or `https`, if it doesn't, it adds it. It also check if there is a port present if, it it isn't, it adds `:3001` as default.
> Format apiEndpoint URL to  add http and port if not present

- README.md
- scripts/NodeAdmin.Dockerfile
- While testing the docker image generated from the command, it was noticed that there were some io_setup() related errors. To fix them the `nginx` image was changed to the stable version.
- The docker run command was also added to the README
> Change nginx docker version + add run command on README

- src/components/ConnectNode/modal.tsx
- src/router.tsx
Fixes #416 
Adds goal tracking for:
> Add login to node by url success or fail goal tracking

- src/components/Modal/node/SendMessageModal.tsx
Fixes #449 
Remove trailing or consecutive commas. Example problem messagePayload:
```
{
“apiToken":"Example-api-token",
"apiEndpoint":"http://apiEndpoint:3001/",
"body":"ejemplo",
"peerId":"ejemplo",
"tag":1,
"path":[
"",
"abc",
"",
"def",
"cba”,
””
]
}
```
How it looks before sending to sdk (after filtering):
```
{
"apiToken": "Example-api-token",
"apiEndpoint": "http://apiEndpoint:3001/",
"body": "ejemplo",
"peerId": "ejemplo",
"tag": 1,
"path": [
"abc",
"def",
"cba"
]
}
```
---
This is done when we are abou to send the message, so the messageModal itself doesn't update the content of the path field
> Add filter to remove consecutive or trailing commas

- src/components/Modal/node/SendMessageModal.tsx
Fixes #444
This changes the Textfield that was used to the Receiver, for a Select component, to let the user choose from the peers instead of having to type the peerId. 
It displays the peers as `alias (PeerId)` if an alias exists for that peer, else it shows `peerId`
> Update to a Select for the receiver field

- src/pages/node/aliases.tsx
Fixes #471 
This function didn't have async await, to result of this was all the request being executed at the same time, since we have a condition where if a function is called while it's already executing, we were cancelling before it's execution (refer to: https://redux-toolkit.js.org/api/createAsyncThunk\#canceling-before-execution).
When using await to lock the execution to not be parallel it works as expected
> Update import of aliases to use async-await

- config.ts
- package.json
- src/components/InfoBar/details.tsx
- src/components/Modal/node/AddAliasModal.tsx
- src/components/Modal/node/PingModal.tsx
- src/components/Modal/node/SendMessageModal.tsx
- src/future-hopr-lib-components/Button/SmallActionButton.tsx
- src/hooks/useWatcher/index.ts
- src/pages/node/channelsIncoming.tsx
- src/pages/node/channelsOutgoing.tsx
- src/pages/node/configuration.tsx
- src/pages/node/info.tsx
- src/pages/node/tickets.tsx
- src/pages/staking-hub/dashboard/node.tsx
- src/pages/staking-hub/dashboard/staking.tsx
- src/store/slices/node/actionsAsync.ts
- src/store/slices/node/initialState.ts
- src/utils/functions.ts
- yarn.lock
Changelog:
- update HOPRd SDK to 2.0.1
- add node actions such as ping, add alias, send message to channels page
- disable ping, add alias, send message modals on channels page if we do not know the peerId of the node
- update ping, add alias, send message modals to update the peerid in the textfield if it uodates (long load times can happen) 
- add copy and 'see on gnosisscan.io' buttons on important eth addressis on the info page
- add wxHOPR allowance to InfoBar
- remove 'redeem tickets button' from `/tickets` page
- add wxHOPR parsing to `/tickets` page
- remove pending from  `/tickets` page
> Node/update 2.0.1

- package.json
- src/pages/node/info.tsx
- src/router.tsx
Changelog:
- Node PeerID copy button on the info page
- remove web3 (Staking Hub) login from Drawer Node Admin mobile
> Node PeerID copy button and remove web3 login froe Node Admin mobile
