.github/workflows/build.yml
.github/workflows/publish.yml
README.md

- Added documentation on how to run the Image
- Improved the way that the image is being built and pushed

Improve docs and github actions

---

src/commands/fundMultiChannels.ts
src/commands/index.ts
src/utils/api.ts

- add `fund` command in admin UI
- Call API endpoint bringing back in https://github.com/hoprnet/hoprnet/pull/4566/
E.g. `fund <counterpart> <outgoing_amount> <incoming_amount>`

Add `fund` command to admin

---

README.md

- Fix how to download latest version documentation

Fixing docker version format on documentation

---

src/commands/index.ts

recognition for commands with capital letter

---

src/router.tsx
src/sections/info.tsx

closes #18 
information subpage that displays info about node, no styles just redux queries and html.

add information subpage

---

.eslintrc.json
package.json
src/sections/aliases.tsx
src/sections/info.tsx
src/store/slices/node/websocketMiddleware.ts
src/types/store.ts
yarn.lock

with the migration to vite, eslint was forgotten, this pr adds eslint back to the project.
not: format code and force a code style
does: checks syntax and finds possible problems

add eslint configuration

---

src/App.tsx
src/components/NotificationBar/index.tsx
src/future-hopr-lib-components/JazzIcon/index.tsx
src/providers/Watcher/index.tsx
src/store/slices/node/index.ts

closes #24 
Create watcher component that compares previous states of certain variables with new updates and dispatches notifications on updates.
Using a temporal variable we check every certain amount of time if the new variable is different to the last saved temporal variable.  
messages, because there is no way to fetch an update we just have to wait for the redux store to update with some new messages.

Add watcher

---

src/sections/peers.tsx

Closes #50 
This pull request enhances the functionality of the Admin Subpage `Peers`. 
The following functionalities are to be expected:
- Last seen formatted to device local time (format `YYYY-MM-DD HH:MM GMT+XX`)
- Quality

Peers: more functionality

---

src/components/Modal/SendMessageModal.tsx
src/router.tsx
src/sections/ping.tsx
src/store/slices/node/actionsAsync.ts

Subpage: Ping

---

src/future-hopr-lib-components/Button/index.tsx

now button in future lib components is typed with tsx

migrate button from jsx to tsx

---

package.json
yarn.lock

Sometimes the connect wallet button didn't do anything. 
Updatating packages seems to fix the issue.

Updated packages

---

config.ts
src/router.tsx

const environment that can be populated with following strings: 'dev' | 'node' | 'web3'
'dev' will show all parts of the app
'node' will show only Node Admin parts of the app
'web3'will show only Staking Hub and Web3 parts of the app

variable to show only the parts of app we need

---

src/sections/selectNode.tsx
src/store/slices/auth/actionsAsync.ts
src/store/slices/auth/index.ts

closes #104 
Adds a error message to auth state if node has less than 0.001 xDai
There is already similar logic in loginThunk.rejected, so the main reason is to reuse already existing code.

Add low balance error on connect to node

---

src/components/ConnectSafe/index.tsx
src/components/ConnectWeb3/index.tsx
src/hooks/useWatcher/safeTransactions.ts

closes #149 
Fixes endpoint link that is used to take user to pending transactions page

Fix pending transaction link

---

src/components/ConnectNode/modal.tsx
src/components/ConnectSafe/index.tsx
src/components/InfoBar/index.tsx
src/components/SubpageTitle/index.tsx
src/future-hopr-lib-components/Button/IconButton.tsx
src/future-hopr-lib-components/Navbar/navBar.tsx
src/future-hopr-lib-components/Table/columed-data.jsx
src/hooks/useWatcher/index.ts
src/router.tsx
src/sections/info.tsx
src/sections/logs.tsx
src/sections/tickets.tsx
src/store/slices/node/actionsAsync.ts
src/store/slices/node/initialState.ts
src/utils/helpers.ts

- Info subpage update
- not turning on balance watcher if not connected
- https://github.com/hoprnet/hopr-admin/issues/158
- Ticket subpage

Info subpage update

---

src/sections/safeSettings.tsx

The app didnt want to build and after fixing of that, when going to safe settings, we were losing the list of safes

Fix safe resetting and typescript errors

---

src/providers/wagmi/updater.tsx
src/store/slices/web3/actionsAsync.ts

fixes #184 
handle null case for graphql query

Bugfix query community nft

---

src/components/Modal/WithdrawModal.tsx
src/sections/node/info.tsx
yarn.lock

blocked by https://github.com/hoprnet/hopr-sdk/pull/83
closes #142 
added modal to node info page, when you click the wallet on the right to the balance
Every time we fetch info from the node, the modal closes. It seems to be because one of the states in redux is causing this but not sure where.

Withdraw from node modal

---

src/router.tsx
src/steps/setupYourNode.tsx

closes #199 
It's not exactly centered mainly because the code snippets take up more space there.

UI for setup your node page

---

package.json
src/store/slices/safe/actionsAsync.ts
vite.config.ts
yarn.lock

closes #204 
Buffer was not being imported before in production. I changed dependencies to handle the polyfill and it seems to work fine now.

Fix polyfill in production

---

src/components/ConnectWeb3/index.tsx
src/providers/wagmi/index.tsx
src/sections/actions.tsx
src/sections/safeWithdraw.tsx
src/sections/wrapper.tsx
src/steps/xdaiToNode.tsx
src/store/slices/web3/index.ts
src/store/slices/web3/initialState.ts

The PR is not building, as the previous PR is needed for the build process

Overall error handling on click MM button, and fix for error when MM is not present

---

src/components/InfoBar/index.tsx

- styling of Infobar
- Trunkating moved mostly to css. For now only some whole nubmers will be trunkated by JS

Infobar style update

---

src/sections/node/tickets.tsx
src/store/slices/node/actionsAsync.ts
src/store/slices/node/initialState.ts

Closes #164 
This pull request aims to provide the functionality of handling when redeemTicketsThunk is loading and when it has errors in a global manner to reduce the amount of repeated amount of code.
The new redeemTickets state structure is:
```
redeemTickets: {
isFetching: false,
error: {
error: undefined,
status: undefined,
},
},
```

Move redeemTickets logic to redux

---

src/providers/wagmi/index.tsx

closes #207 
remove public client from wagmi connector

Remove public client

---

config.ts
nginx.conf
public/.htaccess
scripts/NodeAdmin.Dockerfile
src/components/CodeCopyBox/styled.tsx
src/components/ConnectSafe/index.tsx
src/components/ConnectWeb3/index.tsx
src/future-hopr-lib-components/Layout/drawer.tsx
src/store/index.ts
src/store/slices/safe/actionsAsync.ts
src/store/slices/stakingHub/actionsAsync.ts
src/store/slices/stakingHub/index.ts
src/store/slices/stakingHub/initialState.ts

Sorry for 1 PR for both. Needed to make both happen fast

Own safe DB, and router fix for Node Admin

---

src/components/ConnectSafe/index.tsx
src/components/ConnectWeb3/index.tsx
src/components/Modal/node/AddAliasModal.tsx
src/components/Modal/node/OpenMultipleChannelsModal.tsx
src/components/Modal/node/OpenOrFundChannelModal.tsx
src/components/Modal/node/PingModal.tsx
src/components/Modal/node/SendMessageModal.tsx
src/components/Modal/node/WithdrawModal.tsx
src/components/Modal/staking-hub/ContinueOnboarding.tsx
src/future-hopr-lib-components/Button/index.tsx
src/pages/node/aliases.tsx
src/pages/node/channelsIncoming.tsx
src/pages/node/channelsOutgoing.tsx
src/pages/node/info.tsx
src/pages/node/messages.tsx
src/pages/node/peers.tsx
src/pages/staking-hub/landingPage.tsx
src/pages/staking-hub/onboarding.tsx
src/providers/wagmi/updater.tsx
src/router.tsx
src/store/slices/safe/actionsAsync.ts
src/store/slices/safe/index.ts
src/store/slices/stakingHub/actionsAsync.ts
src/store/slices/stakingHub/index.ts
src/store/slices/stakingHub/initialState.ts

- changing mm account will reset onboarding
- if safe is already created, landing page will prompt a popup with info that you can continue

staking mm address change

---

src/store/slices/auth/actionsAsync.ts
src/store/slices/node/actionsAsync.ts
src/store/slices/node/initialState.ts

closes #230 
checks if is eligible from info is true, if not it throws an error.

Node admin: on login check NR

---

src/components/ConnectWeb3/index.tsx
src/pages/node/metrics.tsx
src/store/slices/auth/actionsAsync.ts
src/store/slices/auth/index.ts
src/store/slices/node/actionsAsync.ts
src/store/slices/node/actionsFetching.ts
src/store/slices/node/index.ts
src/store/slices/node/initialState.ts
src/store/slices/safe/actionsAsync.ts
src/store/slices/safe/actionsFetching.ts
src/store/slices/safe/index.ts
src/store/slices/stakingHub/actionsAsync.ts
src/store/slices/stakingHub/index.ts
src/store/slices/web3/actionsAsync.ts
src/store/slices/web3/index.ts

closes https://github.com/hoprnet/hopr-admin/issues/192
- remove `any` type from redux slices
- move fetching states to separate file
- remove redundant types in thunk actions

clean up redux and improve ts types

---

src/store/slices/safe/actionsAsync.ts

closes #232 
checks if a value is serializable before rejecting it

wrap errors from hopr safe infra

---

src/pages/staking-hub/onboarding/step0/2safeIsReady.tsx
src/store/slices/safe/actionsAsync.ts
src/store/slices/stakingHub/actionsAsync.ts

closes #256 
reset safe info and other safe properties after safe was created successfully

reset safe state after creation

---

src/components/ConnectSafe/index.tsx
src/pages/staking-hub/onboarding/step3/1setupYourNode.tsx
src/pages/staking-hub/onboarding/step5/0addNode.tsx
src/pages/staking-hub/onboarding/step6/0configureNode.tsx
src/store/slices/stakingHub/index.ts

closes #262
when including node now we will get module address from `stakingHub` slice instead of the `safe` slice

fix include node

---

src/pages/staking-hub/onboarding/step8/0setAllowance.tsx

step for set allowance now executes and does not propose

Update set allowance to execute and not propose

---

src/components/ConnectSafe/index.tsx

Update getOnboardingData so it no longer need ts-ignore without changing the logic. Specifically in this case we unwrap a dispatch this way we make sure we get the value.

Remove ts-ignore from getOnboardingData

---

src/pages/staking-hub/onboarding/step2/0fundSafe.tsx
src/providers/wagmi/index.tsx

closes #252 
Refetches safe balance every 15s on fund node page and removes derp from public providers because of possibility of 429 errors

Add polling safe balance every 15s on fund node page and remove derp from public provider

---

src/components/ConnectWeb3/index.tsx

closes #287 
Fix wallet connect modal causing errors on close

Fix wallet connect bug

---

src/components/ConnectSafe/index.tsx
src/pages/staking-hub/safeWithdraw.tsx
src/store/slices/safe/actionsAsync.ts

closes #298 
Fixes change safe address in withdraw page, before the info would not be fetched again

Fix withdraw

---

src/pages/staking-hub/actions.tsx

fixes #306 
Safe info is really important in order to know what nonce the safe is currently on, the constant disabled buttons were fixed in #309, here this pr is mainly activating disabled buttons again and sorting the actions by nonce

Fix actions disabled

---

src/pages/staking-hub/onboarding/step3/1setupYourDappNode.tsx

Update set up your Dapp node onboarding

---

src/future-hopr-lib-components/Table/table-pro.tsx
src/pages/node/aliases.tsx
src/pages/node/channelsIncoming.tsx
src/pages/node/channelsOutgoing.tsx
src/pages/node/messages.tsx
src/pages/node/peers.tsx

closes #347
Fixes consistency in modals and table rows by making the key as unique as possible

Fix ping modal 

---

src/components/ConnectSafe/index.tsx
src/store/slices/stakingHub/actionsAsync.ts

closes https://github.com/hoprnet/hopr-admin/issues/327
moves `get onboarding data` to `stakingHub` slice

Move get onboarding data to redux

---

config.ts
src/future-hopr-lib-components/Layout/drawer.tsx

Fix staking hub in drawer reload

---

src/store/slices/auth/actionsAsync.ts

closes https://github.com/hoprnet/hopr-admin/issues/357

Improve node not eligible message

---

src/store/slices/stakingHub/actionsAsync.ts

There was an error parsing bigint
```
actionsAsync.ts:392 Getting Onboarding Step failed SyntaxError: Cannot convert 0.1 to a BigInt
```

Fix goToStepWeShouldBeOnThunk

---

src/hooks/useWatcher/balances.ts

Fixes #371 
Add balance notifications for when Safe receives xDai or wxHopr.
For receiving funds there should be only following notifications:

Add notifications for safe xdai and safe wxHopr

---

src/pages/node/aliases.tsx
src/pages/node/peers.tsx

closes #393
- add peerAddress to action open outgoing channel in peers
- add peerAddress to action open outgoing channel in aliases

Add peer address to open outgoing channels

---

src/components/ConnectNode/modal.tsx
src/store/slices/auth/actionsAsync.ts
src/store/slices/auth/index.ts
src/store/slices/auth/initialState.ts

closes #391 
why wip?
- missing a max-height property on modals that allows modal to grow with text

Add force login to node admin

---

src/future-hopr-lib-components/Layout/index.tsx
src/store/slices/auth/index.ts
src/store/slices/auth/initialState.ts
src/utils/functions.ts
src/utils/localStorage.ts

Fixes #404 
This pull request saves to localStorage the last state of the Sidebar, either open or closed. When the page loads it loads the state from localStorage before setting the initial state.

Sidebar state to localStorage

---

src/components/Modal/node/SendMessageModal.tsx

Fixes #431 
This pull request introduces visual improvementes to the sendMessage Modal
---

Update sendMessage modal style

---

README.md
nginx.conf

Document how to run the docker image

Document running docker image

---

src/components/Modal/staking-hub/DockerRunCommandModal.tsx
src/pages/staking-hub/dashboard/node.tsx
src/pages/staking-hub/onboarding/step3/1setupYourNode.tsx

Docker Command for running Docker Node from the Dashboard
The cmd is imported from the onbloarding cmd

Docker Command in Nodes

---

src/future-hopr-lib-components/Table/table-pro.tsx
src/pages/staking-hub/dashboard/index.tsx
src/pages/staking-hub/dashboard/node.tsx
src/pages/staking-hub/landingPage.tsx
src/store/slices/stakingHub/actionsAsync.ts
src/store/slices/stakingHub/initialState.ts
src/utils/functions.ts

Added balance in the table.
'Show details' button switches the top of the page to the selected node

Multiple node balances and details

---

package.json
src/components/ConnectWeb3/index.tsx
src/components/Modal/staking-hub/ContinueOnboarding.tsx
src/components/Modal/staking-hub/StartOnboarding.tsx
src/components/NetworkOverlay/index.tsx
src/future-hopr-lib-components/Layout/drawer.tsx
src/pages/staking-hub/dashboard/index.tsx
src/pages/staking-hub/fundNode.tsx
src/pages/staking-hub/safeWithdraw.tsx
src/providers/wagmi/updater.tsx
src/router.tsx
src/store/index.ts
src/store/slices/safe/index.ts
src/store/slices/stakingHub/index.ts
src/store/slices/web3/index.ts
src/store/slices/web3/initialState.ts
yarn.lock

Wallet switching changes
in-app disconnect handling change
chain switch - better support
no safe created check with a popup if no safe
loading screen added when wallet is not knowen yet

Fix wallet switch, disconnect, chain switch, wallet lock, no wallet etc.

---

package.json
src/pages/staking-hub/dashboard/node.tsx
src/pages/staking-hub/onboarding/step5/0addNode.tsx

- Fix node onboarding train icon
- remove unused graybox for Earned rewards
- fix .includes() error on nextNode onboarding

Fix node onboarding train icon and other minor stuff

---

package.json
src/components/FeedbackTransaction/index.tsx
src/components/SafeTransactionButton/index.tsx
src/pages/staking-hub/fundNode.tsx
src/pages/staking-hub/onboarding/step7/0fundNode.tsx
src/pages/staking-hub/safeWithdraw.tsx
src/store/slices/safe/actionsAsync.ts
src/store/slices/stakingHub/actionsAsync.ts

Needes full testing on:
- withdraw subpage
- fund node subpage
- edit owners subpage

Fix checksums on ETH addreses and better error showing

---

src/components/Modal/staking-hub/ContinueOnboarding.tsx
src/future-hopr-lib-components/Layout/drawer.tsx

Continue onboarding modal made more understandable
